#!/bin/sh

case "$1" in
    start)
        printf "Starting mqtt subscriber: "
        start-stop-daemon -S -n mqtt_subscriber -a /usr/bin/mqtt_subscriber -- -d -h %HOST% -t %TOPIC% -f /dev/mqttlog
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping mqtt subscriber: "
        start-stop-daemon -K -n mqtt_subscriber
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

