#!/bin/sh

case "$1" in
    start)
        printf "Loading mqtt_char_driver module: "
        modprobe mqtt_char_driver || insmod /lib/modules/$(uname -r)/extra/mqtt_char_driver.ko
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Unloading mqtt_char_driver module: "
        rmmod mqtt_char_driver # && rm -f /dev/...
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

