#!/bin/sh

case "$1" in
    start)
        echo "Loading mqtt_char_driver module..."
        modprobe mqtt_char_driver || insmod /lib/modules/$(uname -r)/extra/mqtt_char_driver.ko || exit 1
        echo "Loaded mqtt_char_driver module."
        ;;
    stop)
        echo "Unloading mqtt_char_driver module..."
        rmmod mqtt_char_driver || exit 1
        # && rm -f /dev/...
        echo "Unloaded mqtt_char_driver module."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

