#!/bin/sh

case "$1" in
    start)
        echo "Loading mqttlog module..."
        modprobe mqttlog || insmod /lib/modules/$(uname -r)/updates/mqttlog.ko || exit 1
        echo "Loaded mqttlog module."
        ;;
    stop)
        echo "Unloading mqttlog module..."
        rmmod mqttlog || exit 1
        echo "Unloaded mqttlog module."
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

