name: qemu-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    run-qemu-test:
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Build qemu image
            run: ./tests/validate_qemu.sh build
          - name: Start qemu image
            run: ./tests/validate_qemu.sh start
          - name: Test ssh access
            run: ./tests/validate_qemu.sh ssh
          - name: Test mqtt subscriber
            run: ./tests/validate_qemu.sh mqtt
          - name: Stop qemu image
            run: ./tests/validate_qemu.sh stop
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
