name: qemu-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    start-stop-test:
#        container: cuaesd/aesd-autotest:24-assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Build image
            run: ./tests/validate_qemu.sh build
          - name: Start image
            run: ./tests/validate_qemu.sh start
          - name: Test ssh access
            run: ./tests/validate_qemu.sh ssh
          - name: Stop image
            run: ./tests/validate_qemu.sh stop
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
