name: rpi-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    compile-test:
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Build rpi image
            working-directory: ./_rpi
            run: ./tests/validate_rpi.sh build
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
