name: rpi-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    build-rpi-test:
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
            with:
              clean: false
          - name: Build rpi image
            run: ./tests/validate_rpi.sh build